---
title: "Tree Data Explorations"
format: html
---

# R Intro


# Packages


```{r}
library(tidyverse)
library(shiny)
library(leaflet)

```

# Choropleth Map of Forest Attributes in PA

```{r}
# County codes
county_fips_PA <- read_csv("data/county_fips_master.csv") %>%
  filter(state_abbr == "PA") %>%
  select(county, county_name)

pa_county_trees <- readRDS("~/Documents/workshops/trees-s26/data/PA_county.rds") %>%
  left_join(county_fips_PA, by = join_by("COUNTYCD" == "county")) %>%
  mutate(county_short = str_remove(county_name, " County") %>% str_to_lower())
  

```

```{r}
pa_county_boundaries <- map_data("county", "pennsylvania")
glimpse(pa_county_boundaries)
```

XXX: need to add labels but need centroid first

```{r}
ggplot(data = pa_county_boundaries,
       mapping = aes(x = long, y = lat, 
                     group = group)) +
  geom_polygon(fill = "white",
               color = "olivedrab") + 
  coord_quickmap() +
  theme_void()
```

```{r}
pa_county_trees <- pa_county_trees %>%
  left_join(pa_county_boundaries,
            by = join_by("county_short" == "subregion"))
```

```{r}
ggplot(data = pa_county_trees,
       mapping = aes(x = long, y = lat, 
                     group = group,
                     fill = biomass)) +
  geom_polygon(color = "olivedrab") + 
  coord_quickmap() +
  theme_void()
```

```{r}
ggplot(data = pa_county_trees,
       mapping = aes(x = long, y = lat, 
                     group = group,
                     fill = biomass)) +
  geom_polygon(color = "olivedrab") + 
  coord_quickmap() +
  theme_void() +
  scale_fill_viridis_c(direction  =  -1)
```


```{r}
ggplot(data = pa_county_trees,
       mapping = aes(x = long, y = lat, 
                     group = group,
                     fill = biomass,
                     label = county_short)) +
  geom_polygon(color = "grey34") + 
  coord_quickmap() +
  theme_void() +
  geom_label() +
  scale_fill_distiller(palette = "Greens",
                       direction = 1) 
  
  
  
```


# Mapping Trees!